Do not register_plugin! during test
Prior to this change, register_plugin! causes issues when running tests
in Zellij with insta::assert_snapshot!

    thread 'keybind::tests::test_bind_plugin_keys' panicked at src/main.rs:153:1:
    called `Result::unwrap()` on an `Err` value: failed to deserialize object from stdin

    Caused by:
        EOF while parsing a value at line 2 column 0

This change fixes the issue.